name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Build uberjar
      run: lein uberjar
    - name: Upload artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: server
        path: target/uberjar/bouncyrain-*-standalone.jar
